In [9]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Strings

In [10]:
'I love tennis'

'I love tennis'

In [11]:
'2.3'

'2.3'

In [12]:
'2.3' + 4

TypeError: must be str, not int

In [13]:
'2.3' * 4

'2.32.32.32.3'

In [14]:
'be' + 'happy'

'behappy'

In [15]:
str(2.3)

'2.3'

In [16]:
int('2.3')

ValueError: invalid literal for int() with base 10: '2.3'

In [17]:
float('2.3')

2.3

In [18]:
int('23') + float('2.3')

25.3

In [19]:
x = 12

In [20]:
int(str(x) + '0')

120

<br><br><br><br><br><br><br><br><br><br><br><br>

## Minard's map

In [21]:
minard = Table.read_table('http://inferentialthinking.com/notebooks/minard.csv')

In [22]:
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [23]:
minard.num_columns

5

In [24]:
minard.num_rows

8

In [25]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [26]:
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [27]:
minard.column(4)

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [28]:
initial_size = minard.column('Survivors').item(0)

In [29]:
initial_size

145000

In [30]:
percentage_surviving = minard.column('Survivors')/initial_size

In [31]:
percentage_surviving

array([ 1.        ,  0.96551724,  0.87655172,  0.68965517,  0.37931034,
        0.16551724,  0.13793103,  0.08275862])

In [32]:
with_percentages = minard.with_column('Percent Surviving', percentage_surviving)

In [33]:
with_percentages

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

In [34]:
with_percentages.set_format('Percent Surviving', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

<br><br><br><br><br><br><br><br><br><br><br><br>

## Lists

In [35]:
2

2

In [36]:
2.0

2.0

In [37]:
make_array(2, 3.0)

array([ 2.,  3.])

In [38]:
make_array(2, 3.0).item(0)

2.0

In [39]:
make_array(2, 'three')

array(['2', 'three'], 
      dtype='<U21')

In [40]:
make_array(2, 'three').item(0)

'2'

In [41]:
[2, 'three']

[2, 'three']

In [42]:
type([2, 'three'])

list

In [43]:
my_favorite_flower = [5, 'morning glory']

In [44]:
flowers.with_row(my_favorite_flower)

NameError: name 'flowers' is not defined

## Table operations: Take

In [ ]:
minard

In [ ]:
minard.take(0)

In [ ]:
minard.take([0,2,3])

In [ ]:
np.arange(0, 4)

In [ ]:
minard.take(np.arange(0,4))

<br><br><br><br><br><br><br><br><br><br><br><br>

## Table operations: where

In [ ]:
# This table can be found online: https://www.statcrunch.com/app/index.php?dataid=1843341
nba = Table.read_table('nba_salaries.csv')

In [ ]:
nba

In [ ]:
nba.sort('2015-2016 SALARY')

In [ ]:
nba = nba.relabeled('2015-2016 SALARY', 'SALARY')

In [ ]:
nba.sort('SALARY')

In [ ]:
nba.where('SALARY', are.above(10))

In [ ]:
nba.where('SALARY', are.above(10)).sort('SALARY')

In [ ]:
nba.where('SALARY', are.between(10, 11))

In [ ]:
nba.where('TEAM', are.equal_to('Toronto Raptors'))

In [ ]:
nba.where('TEAM', 'Toronto Raptors')

In [ ]:
nba.where('TEAM', are.containing('Raptors'))

In [ ]:
nba.where('PLAYER', are.equal_to('Stephen Curry'))

In [ ]:
nba.where('TEAM', are.equal_to('Golden State Warriors'))

In [ ]:
nba.where('TEAM', are.equal_to('Golden State Warriors')).sort('2015-2016 SALARY', descending=True)

In [ ]:
nba.where('2015-2016 SALARY', are.between(10, 12))